server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
      enabled: true
      change-log: classpath:/db/changelog/db.changelog-master.yml
  application:
    name: order-ms
